[package]
name = "ruin_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.4"
winit = "0.29"
glam = "0.25"
web-sys = "0.3"

[workspace]
members = [
    "run-wasm",
]
